{% set version = "1.6.1" %}

package:
  name: gpxpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gpxpy/gpxpy-{{ version }}.tar.gz
  sha256: 473ff2fa17af6913a9879599cb6fe9c7a30fa1698898feff21a825447ee52fba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - gpxpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.trackprofiler.com/gpxpy/index.html
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: GPX file parser and GPS track manipulation library

extra:
  recipe-maintainers:
    - ocefpaf
