{% set version = "1.6.0" %}

package:
  name: gpxpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gpxpy/gpxpy-{{ version }}.tar.gz
  sha256: c6f6d17fe0add76d8cdf979f8462799cee54c9bb3480811f04e1f5a5e7b6db64

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - gpxpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.trackprofiler.com/gpxpy/index.html
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: GPX file parser and GPS track manipulation library

extra:
  recipe-maintainers:
    - ocefpaf
