{% set version = "1.5.0" %}

package:
  name: gpxpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gpxpy/gpxpy-{{ version }}.tar.gz
  sha256: e6993a8945eae07a833cd304b88bbc6c3c132d63b2bf4a9b0a5d9097616b8708

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - gpxpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.trackprofiler.com/gpxpy/index.html
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: GPX file parser and GPS track manipulation library

extra:
  recipe-maintainers:
    - ocefpaf
