{% set name = "gpxpy" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gpxpy-{{ version }}.tar.gz
  sha256: 473ff2fa17af6913a9879599cb6fe9c7a30fa1698898feff21a825447ee52fba

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - gpxpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tkrajina/gpxpy
  summary: GPX file parser and GPS track manipulation library
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - ocefpaf
