{% set version = "1.4.1" %}

package:
  name: gpxpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gpxpy/gpxpy-{{ version }}.tar.gz
  sha256: d9734fc75a61302c0ce99d1a200af29ab4ce29045d745d39d90f2ab20b246360

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - gpxpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.trackprofiler.com/gpxpy/index.html
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: GPX file parser and GPS track manipulation library

extra:
  recipe-maintainers:
    - ocefpaf
