travis:
  secure:
    BINSTAR_TOKEN: guHYZU6pijVnMzOM87ZyUw5uGVV/TdVulwxcekle3OWf88qJliv9R0KcAJzcvlAlj/0EymF0q1AB9LT1eM7Np6/w0mZfE28VnE7o5agvgC6IrgAd636n3+iMR3++twEt7+9tlBSiB7g38tga0KRHlR8miu8y6AjJ4gx3R4kdZL3z0hOtgqWJX21IYxOzwWAjP7DoRZC2GvSgigaaOcVYZsIIC4TuqaYd8fz12eyaP+8/nhr55FmKEEDhz9STlUsdKU7+E+gHNG5RImKcP3V3wvNWqhkU9e10T5FGW3ovmuKcJw+SnlThwchydMwa6kv7pxarW8R8TCszPRUypGx1VaRbhBsBfVZNuC7iytcLbtH0xq9RZqdYBsT5MM0YO2iWtC1Agnz5m0hzyr9/aTT7i2x4Qz0g0bHmUerZUZjYlN7CBXFze4ZQnQoZ3RW+NGCxOCSpNmMrxGxL/JkQfRahoswrUgy/58j+w7kLDbfHzdCcasrtD4Oo3+BS62Y3JHOPDzjJYSusU4fTPIxmSDVBR5bq6x/0HBBSCQB24XcmfOaZzYWf2inz91X0PRFfrFodBcQPkpi01XQZPNYppOVqFHH3ezU7GR9Udb7zDZvVknI2Uzmr9S2VJ+IPzmDNaAl6gPKxOR/22Avlm5KbPVy1slCH8n5fVP3mGHsgj+qmXbA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
